Algoritmo "ex004 Apostila"
// Desenvolva um algoritmo que leia dois números inteiros e mostre o somatório
// entre eles.
// Ex:
// Digite um valor: 8
// Digite outro valor: 5
// A soma entre 8 e 5 é igual a 13.
Var
   N1, N2, soma: Inteiro

Inicio
      Escreva("Digite um valor: ")
      Leia(N1)
      Escreva("Digite outro valor: ")
      Leia(N2)
      soma <- N1 + N2
      Escreva("A soma entre", N1, " e", N2, " é igual a", soma, ".")
Fimalgoritmo